apiVersion: v1
kind: Pod
metadata:
  name: consul-server
  labels:
    app: consul-server
spec:
  containers:
  - name: consul-server
    image: nicholasjackson/consul_connect:latest
    env:
      - name: CONSUL_BIND_INTERFACE
        value: "eth0"
      - name: CONSUL_UI_BETA
        value: "true"

---
kind: Service
apiVersion: v1
metadata:
  name: consul-server
spec:
  selector:
    app: consul-server
  ports:
  - name: api
    protocol: TCP
    port: 80
    targetPort: 8500
  - name: gossip 
    protocol: TCP
    port: 8301
    targetPort: 8301
  type: LoadBalancer
