apiVersion: v1
data:
  consul_address: "localhost"
  consul_port: "8500"
  consul_scheme: "http"
  consul_ca_file: ""
  consul_cert_file: ""
  consul_key_file: ""
  consul_insecure_skip_verify: "false"
  consul_token: ""
  consul_timeout: "2s"
  consul_container_name: "consul"
  consul_node_selector: "consul=enabled"
  pod_label_selector: ""
  k8s_tag: "kubernetes"
  register_mode: "single"
  register_source: "node"
kind: ConfigMap
metadata:
    name: kube-consul-register
    namespace: default

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: consul-agent
  labels:
    app: consul-agent
spec:
  selector:
    matchLabels:
      app: consul-agent
  template:
    metadata:
      labels:
        app: consul-agent
    spec:
      containers:
      - name: consul-agent
        image: nicholasjackson/consul_connect_agent:latest
        args: ["-retry-join","consul-server.default.svc.cluster.local"]
        env:
          - name: CONSUL_BIND_INTERFACE
            value: "eth0"
        ports:
        - containerPort: 8500
          hostPort: 8500   
      - name: kube-consul-register
        image: tczekajlo/kube-consul-register:0.1.4
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1
            memory: 300Mi
        args:
        - -logtostderr=true
        - -configmap=default/kube-consul-register
