---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: consul-agent
  labels:
    app: consul-agent
spec:
  selector:
    matchLabels:
      app: consul-agent
  template:
    metadata:
      labels:
        app: consul-agent
    spec:
      containers:
      - name: consul-agent
        image: nicholasjackson/consul_connect_agent:latest
        args: ["-retry-join","consul-server.default.svc.cluster.local"]
        env:
          - name: CONSUL_BIND_INTERFACE
            value: "eth0"
        ports:
        - containerPort: 8500
          hostPort: 8500   
