apiVersion: v1
data:
  consul_address: "localhost"
  consul_port: "8500"
  consul_scheme: "http"
  consul_ca_file: ""
  consul_cert_file: ""
  consul_key_file: ""
  consul_insecure_skip_verify: "false"
  consul_token: ""
  consul_timeout: "2s"
  consul_container_name: "consul"
  consul_node_selector: "consul=enabled"
  pod_label_selector: ""
  k8s_tag: "kubernetes"
  register_mode: "node"
  register_source: "pod"
kind: ConfigMap
metadata:
    name: kube-consul-register
    namespace: default

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: consul-register
  labels:
    app: consul-register
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-register
  template:
    metadata:
      labels:
        app: consul-register
    spec:
      containers:
      - name: kube-consul-register
        image: tczekajlo/kube-consul-register:0.1.4
        imagePullPolicy: Always
        args:
        - -logtostderr=true
        - -configmap=default/kube-consul-register
