---
apiVersion: v1
kind: Service
metadata:
  name: router
spec:
  selector:
    app: router
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8181
  type: LoadBalancer

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: router
  labels:
    app: router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
      - name: router
        image: nicholasjackson/consul-connect-router:v0
        args: [
          '--upstream=emojify-website#/',
          '--upstream=emojify-api#/api',
          '--consul_addr=http://$(HOST_IP):8500'
          ]
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP

